
apiVersion: v1
kind: Pod
metadata:
  name: pod-mjsrkq-train
spec:
  automountServiceAccountToken: false
  containers:
  - name: pod-mjsrkq-train
    image: gitlab-registry.nrp-nautilus.io/skhan/dl_pytorch:4bd8b3be
    tty: true
    stdin: true
    workingDir: /data
    command: ["/bin/sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    volumeMounts:
    - name: mjsrkq-pv
      mountPath: /data
    resources:
      limits:
        memory: 10Gi
        cpu: "1"
      requests:
        memory: 10Gi
        cpu: "1"
  volumes:
  - name: mjsrkq-pv
    persistentVolumeClaim:
      claimName: mjsrkq-pv
  restartPolicy: Never