apiVersion: v1
kind: Pod
metadata:
  name: pod-mjsrkq-train
spec:
  restartPolicy: Never
  volumes:
  - name: mjsrkq-storage
    persistentVolumeClaim:
      claimName: mjsrkq-pv
  containers:
  - name: train-container
    image: gitlab-registry.nrp-nautilus.io/skhan/dl_pytorch:4bd8b3be
    command: ["/bin/sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    workingDir: /data
    resources:
      limits:
        memory: 32Gi
        cpu: "8"
      requests:
        memory: 32Gi
        cpu: "8"
    volumeMounts:
    - mountPath: /data
      name: mjsrkq-storage